### PR TITLE
Fixed issue with Pillow.ImageDraw removed textsize function

### PR DESCRIPTION
**Pull request by bo-kwok**

### CODE REVIEW

**Comment by gonghao** [comment]
A validate patch to fix for #40

**Comment by akornatskyy** [comment]
I have reviewed the PR, I used a slightly different [approach](https://github.com/akornatskyy/wheezy.captcha/commit/8e8fec459babd69a9edfe766e1ca16c9b675733f) with one time compatibility check. consider to check with version 3.2.1, please.

**Comment by gonghao** [comment]
> I have reviewed the PR, I used a slightly different [approach](https://github.com/akornatskyy/wheezy.captcha/commit/8e8fec459babd69a9edfe766e1ca16c9b675733f) with one time compatibility check. consider to check with version 3.2.1, please.

Good job! Please publish to pypi ASAP, thx!

**Comment by akornatskyy** [comment]
:-) it is there... version `3.2.1`.

**Pull request closed without merging**
